const commonEditorSelectors = [
  '.ProseMirror[contenteditable="true"]',
  '[contenteditable="true"][role="textbox"]',
  '.ql-editor[contenteditable="true"]',
  '.public-DraftEditor-content[contenteditable="true"]',
  '[contenteditable="true"]',
];

export const platforms = Object.freeze({
  toutiao: {
    label: '今日头条',
    loginUrl: 'https://mp.toutiao.com/profile_v4/index',
    publishUrl: 'https://mp.toutiao.com/profile_v4/graphic/publish',
    titleSelectors: ['textarea[placeholder*="标题"]', 'input[placeholder*="标题"]'],
    editorSelectors: commonEditorSelectors,
    publishTexts: ['发布'],
    confirmTexts: ['确认发布', '确定发布', '发布'],
    successTexts: ['发布成功', '提交成功'],
    reviewingTexts: ['文章已进入审核', '作品已进入审核', '提交审核成功'],
    requiresCover: true,
    coverFlow: {
      triggerSelectors: ['.article-cover-add'],
      scopeSelectors: ['.upload-image-panel'],
      fileInputSelectors: ['.upload-btn input[type="file"]'],
      confirmTexts: ['确定', '完成'],
    },
    publicUrlPatterns: [/toutiao\.com\/article\/(\d+)/],
  },
  baijiahao: {
    label: '百家号',
    loginUrl: 'https://baijiahao.baidu.com/',
    publishUrl: 'https://baijiahao.baidu.com/builder/rc/edit?type=news',
    titleSelectors: ['[data-testid="news-title-input"] [contenteditable="true"]', 'textarea[placeholder*="标题"]', 'input[placeholder*="标题"]'],
    editorSelectors: ['body[contenteditable="true"]'],
    publishTexts: ['发布'],
    confirmTexts: ['确认发布', '确定'],
    successTexts: ['发布成功', '提交成功'],
    reviewingTexts: ['文章已进入审核', '内容已进入审核', '提交审核成功'],
    requiresCover: true,
    coverFlow: {
      triggerTexts: ['选择封面'],
      dialogSelectors: ['[role="dialog"]', '.ant-modal', '.semi-modal', '.el-dialog'],
      fileInputSelectors: ['input[type="file"][accept*="image"]'],
      confirmTexts: ['确定', '完成'],
    },
    publicUrlPatterns: [/baijiahao\.baidu\.com\/s\?id=(\d+)/],
  },
  zhihu: {
    label: '知乎',
    loginUrl: 'https://www.zhihu.com/signin',
    publishUrl: 'https://zhuanlan.zhihu.com/write',
    titleSelectors: ['textarea[placeholder*="标题"]', 'input[placeholder*="标题"]', 'textarea'],
    editorSelectors: commonEditorSelectors,
    publishTexts: ['发布'],
    confirmTexts: ['确认发布', '发布'],
    successTexts: ['发布成功'],
    publicUrlPatterns: [/zhuanlan\.zhihu\.com\/p\/(\d+)/],
  },
  sohu: {
    label: '搜狐号',
    loginUrl: 'https://mp.sohu.com/',
    publishUrl: 'https://mp.sohu.com/mpfe/v4/contentManagement/news/addarticle',
    titleSelectors: ['textarea[placeholder*="标题"]', 'input[placeholder*="标题"]'],
    editorSelectors: commonEditorSelectors,
    publishTexts: ['发布'],
    confirmTexts: ['确认发布', '确定'],
    successTexts: ['发布成功', '提交成功'],
    reviewingTexts: ['文章已进入审核', '内容已进入审核', '提交审核成功'],
    successUrlPatterns: [/\/contentManagement\/news\/addarticle\?(?:[^#]*&)?contentStatus=1(?:&[^#]*)?(?:#.*)?$/i],
    publicUrlPatterns: [/sohu\.com\/a\/(\d+)/],
  },
  netease: {
    label: '网易号',
    loginUrl: 'https://mp.163.com/',
    publishUrl: 'https://mp.163.com/#/article-publish',
    titleSelectors: ['textarea[placeholder*="标题"]', 'input[placeholder*="标题"]'],
    editorSelectors: commonEditorSelectors,
    publishTexts: ['发布'],
    confirmTexts: ['确认发布', '确定'],
    successTexts: ['发布成功', '提交成功'],
    reviewingTexts: ['文章已进入审核', '提交审核成功', '文章审核中', '内容审核中'],
    blockingTexts: ['您的账号信息正在审核中', '账号信息正在审核中'],
    publicUrlPatterns: [/163\.com\/dy\/article\/([A-Z0-9]+)\.html/i],
  },
  csdn: {
    label: 'CSDN',
    loginUrl: 'https://passport.csdn.net/login',
    publishUrl: 'https://editor.csdn.net/md/',
    titleSelectors: ['input.article-bar__title', 'input[placeholder*="文章标题"]', 'textarea[placeholder*="标题"]'],
    editorSelectors: ['textarea.editor__inner', '.monaco-editor textarea', 'textarea', ...commonEditorSelectors],
    editorFormat: 'markdown',
    publishTexts: ['发布文章', '发布'],
    confirmTexts: ['发布文章', '确认发布', '确定'],
    successTexts: ['发布成功'],
    reviewingTexts: ['文章已进入审核', '提交审核成功'],
    optionalActions: ['原创'],
    publicUrlPatterns: [/blog\.csdn\.net\/[^/]+\/article\/details\/(\d+)/],
  },
  xiaohongshu: {
    label: '小红书',
    loginUrl: 'https://creator.xiaohongshu.com/',
    publishUrl: 'https://creator.xiaohongshu.com/publish/publish?source=official',
    preUploadActionTexts: ['上传图文'],
    imageUploadSelectors: [
      'input[type="file"][accept*="image"]',
      'input[type="file"][accept*=".jpg"]',
      'input[type="file"][accept*=".jpeg"]',
      'input[type="file"][accept*=".png"]',
      'input[type="file"][accept*=".webp"]',
    ],
    titleSelectors: ['input[placeholder*="标题"]', 'textarea[placeholder*="标题"]'],
    editorSelectors: ['textarea[placeholder*="正文"]', 'textarea[placeholder*="描述"]', ...commonEditorSelectors],
    publishTexts: ['发布'],
    publishControlMode: 'exact_text',
    confirmTexts: ['确认发布', '确定'],
    successTexts: ['发布成功', '提交成功'],
    reviewingTexts: ['笔记已进入审核', '内容已进入审核', '提交审核成功'],
    requiresImage: true,
    maxTitleLength: 20,
    maxBodyLength: 1000,
    publicUrlPatterns: [/xiaohongshu\.com\/explore\/([a-z0-9]+)/i],
  },
});

export function getPlatform(key) {
  return platforms[key] ?? null;
}

export function platformKeys() {
  return Object.keys(platforms);
}
